### PR TITLE
Devel::PPPort: Fix commit d6d4687 vmess is already implemented - RT 134101

### PR DESCRIPTION
**Pull request by atoomic**
Fixes GH #10 aka RT 134101

(cherry picked from commit 935b7556e54d4bd3c18fdfef2f072b674afb7051)
Signed-off-by: Nicolas R <atoomic@cpan.org>

### CODE REVIEW

**Comment by atoomic** [comment]
@khwilliamson ok with this change?

**Comment by khwilliamson** [comment]
Yes, but shouldn't we be regenerating these instead of manually fixing?

**Comment by pali** [comment]
@khwilliamson: yes, the best would be to regenerate those todo and base files... But do you know how to do it?

**Comment by atoomic** [comment]
I was looking at `./devel/regenerate` without success...

**Comment by atoomic** [comment]
@khwilliamson / @karenetheridge / @pali  any ideas there how to regenerate these todo?
if not, I think it's fine to merge this commit as it... any objections?

**Comment by pali** [comment]
I do not know. Somehow those `devel/regenerate` and `parts/apicheck.pl` needs to be used...

**Comment by khwilliamson** [comment]
On 6/12/19 8:27 AM, Nicolas R. wrote:
> @khwilliamson <https://github.com/khwilliamson> / @karenetheridge 
> <https://github.com/karenetheridge> / @pali <https://github.com/pali> 
> any ideas there how to regenerate these todo?
> if not, I think it's fine to merge this commit as it... any objections?

no and no

**Comment by karenetheridge** [comment]
@Tux do you know anything about this area?

**Comment by atoomic** [comment]
maybe these tools are designed to be used on dromedary server? need to investigate the best way to do it before merging these changes

**Comment by Tux** [comment]
> @Tux do you know anything about this area?

Not really. I could have a look, but don't wait for it

**Pull request merged**
