### PR TITLE
Add mg_findext (thanks to bulk88 for the implementation)

### PR DESCRIPTION
**Pull request by wolfsage**

### CODE REVIEW

**Comment by dur-randir** [comment]
This is more of a bug report than a comment. Current implementation of 'mg_findext' is unfortunately unusable. mg_findext in the core is defined as 'Perl_mg_findext(const SV* sv, int type, const MGVTBL *vtbl)' and definitely lacks thread context argument. 

But Devel::PPPort version requires it, but doesn't use it in the function body at all, nor directly, nor through macroses. Reading original bug report, I can't understand why LEONT was sure that it needs it. 

But in the current state of this function, one have to patch ppport.h to be able to grab mg_findext on both older and newer threaded perls.

**Comment by wolfsage** [comment]
This has already been fixed and released in Devel::PPPort  3.27 and 3.28.

If that's not the case, could you please provide more details?

Thanks.

**Comment by dur-randir** [comment]
After upgrading to 3.31 this problem is solved, thanks.

**Comment by dur-randir** [comment]
Well, I've discovered another issue. When compiling on, say, 5.10, mg_findext isn't found in the core, so everething is OK. But on 5.14-5.20, version in the core is like previous version from this module (and that's probably the source for a thread context in args).

So, to get mg_findext with a consistent signature, one has to do like

  #if (PERL_VERSION < 21)
  #undef mg_findext
  #define NEED_mg_findext
  #endif

before including ppport.h

**Pull request closed without merging**
