### PR TITLE
Devel::PPPort: Run make regen after regenerating Makefile

### PR DESCRIPTION
**Pull request by atoomic**
Resolves GH #76, RT 134114

This would ensure that all auto-generated files are up-to-date after running configure phase.

(cherry picked from commit 14d33d137d5c30a8a755a201fa4c8c5c4a7ae74d)
Signed-off-by: Nicolas R <atoomic@cpan.org>

### CODE REVIEW

**Comment by karenetheridge** [comment]
As stated in #76 I am not sure that this is the right thing to do.

**Comment by atoomic** [comment]
@karenetheridge do you have any other suggestions how to achieve the `make regen` when regenerating the Makefile file, or are you saying you are not sure this is a good idea at all?
thanks

**Comment by karenetheridge** [comment]
Instead of invoking `make`, can Makefile.PL simply execute the code directly? It looks like it just needs to `do <filename>` for each of the four files.

**Comment by atoomic** [comment]
not required anymore with #95 merged, closing this PR

**Pull request closed without merging**
