### PR TITLE
Fixes for older Perl versions

### PR DESCRIPTION
**Pull request by pali**

### CODE REVIEW

**Comment by khwilliamson** [comment]
I had already made some or all of these fixes with PR #172, which has already been tried out on every release.  I'm waiting for Travis to finish just to be sure.  It did pass my repo successfully already.  The bottom line is I think this PR is extraneous.  I haven't looked at the code yet; perhaps you came up with some better solutions than I did.

**Comment by pali** [comment]
I updated this PR

**Comment by khwilliamson** [comment]
This was included in PR #102

**Comment by khwilliamson** [comment]
This was included in PR #176

**Comment by khwilliamson** [comment]
PR #176  is the correct number for the PR that included this

**Pull request closed without merging**
