### PR TITLE
Implement newSVsv_nomg() and SV_NOSTEAL for sv_setsv_flags() - RT 134103

### PR DESCRIPTION
**Pull request by atoomic**
Resolves GH #63 aka RT 134103

patches from @pali

### CODE REVIEW

**Comment by khwilliamson** [comment]
pali, you need to get this to pass before we can merge it

**Comment by pali** [comment]
Yes, I will fix it.

**Comment by pali** [comment]
I cannot, I'm not allowed to edit this PR :-(

**Comment by khwilliamson** [comment]
pali, send them to me in an email, then

**Comment by pali** [comment]
I have already sent them to that RT ticket.

**Comment by khwilliamson** [comment]
I think the easiest thing is for you to create a new PR with the latest patches

**Comment by pali** [comment]
https://rt.perl.org/Public/Bug/Display.html?id=134103#txn-1637365

**Comment by atoomic** [comment]
Let's re open this PR with the updated patch from https://rt.perl.org/Public/Ticket/Attachment/1637365/838051/v2-0001-Devel-PPPort-Implement-SV_NOSTEAL-for-sv_setsv_flags.patch

**Comment by pali** [comment]
You forgot to update also v2-0002 file.

**Comment by atoomic** [comment]
both patches are now applied to this branch and smoke is in progress

**Comment by atoomic** [comment]
thanks, both are now applied

**Comment by pali** [comment]
Great! Tests now passed.

**Pull request merged**
