### PR TITLE
Fixing 'mysterious name' from make regen

### PR DESCRIPTION
**Pull request by atoomic**
@pali here is the extra fix proposal for mysterious name from `make regen`

### CODE REVIEW

**Comment by pali** [comment]
IIRC apidoc.fnc file is copied from embed.fnc file from main perl git repository? Maybe it should be fixed there first.

**Comment by khwilliamson** [comment]
It's true, that when releasing D:P, one is supposed to copy the latest embed.fnc.

**Comment by pali** [comment]
@khwilliamson so this problem first needs to be fixed in embed.fnc. Can you do it?

**Comment by khwilliamson** [comment]
This is the wrong fix.  The file is supposed to be read only, and is marked at the beginning not to edit it.

It turns out that this is a can of worms, mostly not D:P's fault.  The flags in core embed.fnc and the apidoc entries in the source code have over time diverged in meaning.  D:P doesn't know this, and thinks the meaning is uniform.  This particular issue is actually due to someone probably trying to work around a deficiency rather than getting it done right.  I am working on the stuff in core

**Comment by khwilliamson** [comment]
The solution is different than this

**Pull request closed without merging**
