### PR TITLE
Tweak github CI

### PR DESCRIPTION
**Pull request by atoomic**

### CODE REVIEW

**Comment by pali** [comment]
The point to run `git diff` was at the time when git repo has lot of autogenerated files, it was added during [review](https://github.com/Dual-Life/Devel-PPPort/pull/65#pullrequestreview-237738406) to detect that all files are re-generated and up-to-date and once all autogenerated files were removed from the git repository, also running `git diff` was [removed](https://github.com/Dual-Life/Devel-PPPort/pull/95/commits/c23bfc359923b8e71bcbd1cfb825f90346548523) from the CI, as it was useless then.

I'm not sure why running `git diff` was reintroduced again into CI, but changing it to `git diff --quiet ||:` is absolutely useless as it ignores return value when repo is modified and so, the command never fails. So this command now does absolutely nothing.

**Comment by atoomic** [comment]
I was trying to preserve the best of both worlds... `git diff` being still there and displayed as hint if needed but not blocking 
I'm not sure what reintroduced it, but I m also fine removing it

**Comment by pali** [comment]
I guess it was some of rebase issue (maybe older pull request was based on old commit and then merge conflicts were resolved incorrectly, and unintentionally was it reintroduced - I saw these mistakes lot of times). So just remove git diff, it has no point here.

**Comment by atoomic** [comment]
FYI I just removed the `git diff` from the workflow

**Pull request merged**
