### PR TITLE
Various fixes in Makefile.PL

### PR DESCRIPTION
**Pull request by pali**

### CODE REVIEW

**Comment by karenetheridge** [comment]
Could you be more specific what "fix" means? what was wrong with the META_MERGE code before? Just that it unnecessarily parsed the file for too-old EUMM?

**Comment by pali** [comment]
> what was wrong with the META_MERGE code before?

I thought it fully was obvious from the code. There was a line `delete $mf{META_MERGE}` which did nothing as `%mf` hash declared few lines above has no key `META_MERGE`.

`META_MERGE` itself is declared in `configure` sub. So I moved removal of `META_MERGE` to correct the place.

**Comment by atoomic** [comment]
@pali could you rebase this PR which now conflicts?

**Comment by pali** [comment]
done

**Comment by pali** [comment]
There is one failed test: https://travis-ci.org/Dual-Life/Devel-PPPort/jobs/544797931
> fatal: unable to connect to github.com:
> github.com[0: 192.30.253.112]: errno=Connection timed out

Can you restart it?

**Comment by atoomic** [comment]
@pali job restarted

**Comment by pali** [comment]
Great! Now test passed!

**Comment by pali** [comment]
rebased on master

**Pull request merged**
